// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqxgIIL-LfxJnLuBzaewNT3ORUYwgjklE',
    appId: '1:628792576080:web:0d1d8781846856cfee2955',
    messagingSenderId: '628792576080',
    projectId: 'kitepkana-18f70',
    authDomain: 'kitepkana-18f70.firebaseapp.com',
    storageBucket: 'kitepkana-18f70.firebasestorage.app',
    measurementId: 'G-9T33M0JMEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBsLxhcqQ8uPQXlj4W_idQhH0uaTfwUxg',
    appId: '1:628792576080:android:ec70c96b63007c0fee2955',
    messagingSenderId: '628792576080',
    projectId: 'kitepkana-18f70',
    storageBucket: 'kitepkana-18f70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtVod8z_a_aYBPo3YWU_jU2w93v8T5sOo',
    appId: '1:628792576080:ios:70b0bb0d14e9bab7ee2955',
    messagingSenderId: '628792576080',
    projectId: 'kitepkana-18f70',
    storageBucket: 'kitepkana-18f70.firebasestorage.app',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtVod8z_a_aYBPo3YWU_jU2w93v8T5sOo',
    appId: '1:628792576080:ios:70b0bb0d14e9bab7ee2955',
    messagingSenderId: '628792576080',
    projectId: 'kitepkana-18f70',
    storageBucket: 'kitepkana-18f70.firebasestorage.app',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqxgIIL-LfxJnLuBzaewNT3ORUYwgjklE',
    appId: '1:628792576080:web:4a1b6a8d0fe1557aee2955',
    messagingSenderId: '628792576080',
    projectId: 'kitepkana-18f70',
    authDomain: 'kitepkana-18f70.firebaseapp.com',
    storageBucket: 'kitepkana-18f70.firebasestorage.app',
    measurementId: 'G-0GBLHM1PL6',
  );
}
